"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent

def get_env_bool(name: str, default: bool = False) -> bool:
    """Helper to parse boolean env vars."""
    val = os.getenv(name)
    if val is None:
        return default
    return val.lower() in ("1", "true", "t", "yes", "y")

def get_env_list(name: str, default: list[str] | None = None) -> list[str]:
    """Helper to parse comma-separated lists from env."""
    val = os.getenv(name)
    if not val:
        return default or []
    return [v.strip() for v in val.split(",") if v.strip()]

# Security and core settings from environment
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "insecure-dev-key-change-me")
DEBUG = get_env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = get_env_list("DJANGO_ALLOWED_HOSTS", [
    ".kavia.ai", "localhost", "127.0.0.1", "testserver"
])

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_yasg",
    "corsheaders",
    "channels",
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Django Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Database config - env-driven.
# Supports DATABASE_URL (postgres://, mysql://, sqlite:///path) or individual vars.
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

def db_from_url(url: str):
    """Parse DATABASE_URL into Django DATABASES dict."""
    parsed = urlparse(url)
    scheme = parsed.scheme
    if scheme in ("postgres", "postgresql", "psql", "postgresql+psycopg"):
        engine = "django.db.backends.postgresql"
    elif scheme in ("mysql", "mariadb"):
        engine = "django.db.backends.mysql"
    elif scheme in ("sqlite", "sqlite3"):
        engine = "django.db.backends.sqlite3"
    else:
        raise ImproperlyConfigured(f"Unsupported DATABASE_URL scheme: {scheme}")

    if engine.endswith("sqlite3"):
        path = parsed.path
        if path in ("", "/"):
            name = BASE_DIR / "db.sqlite3"
        else:
            name = path[1:] if path.startswith("/") else path
        return {
            "ENGINE": engine,
            "NAME": str(name),
        }

    return {
        "ENGINE": engine,
        "NAME": parsed.path.lstrip("/") or os.getenv("DB_NAME", ""),
        "USER": parsed.username or os.getenv("DB_USER", ""),
        "PASSWORD": parsed.password or os.getenv("DB_PASSWORD", ""),
        "HOST": parsed.hostname or os.getenv("DB_HOST", ""),
        "PORT": str(parsed.port or os.getenv("DB_PORT", "")),
    }

if DATABASE_URL:
    DATABASES = {"default": db_from_url(DATABASE_URL)}
else:
    # Fallback to sqlite or individual vars
    DB_ENGINE = os.getenv("DB_ENGINE", "sqlite")
    if DB_ENGINE == "sqlite":
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / (os.getenv("SQLITE_NAME", "db.sqlite3")),
            }
        }
    elif DB_ENGINE in ("postgres", "postgresql"):
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.getenv("DB_NAME", ""),
                "USER": os.getenv("DB_USER", ""),
                "PASSWORD": os.getenv("DB_PASSWORD", ""),
                "HOST": os.getenv("DB_HOST", "localhost"),
                "PORT": os.getenv("DB_PORT", "5432"),
            }
        }
    elif DB_ENGINE == "mysql":
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "NAME": os.getenv("DB_NAME", ""),
                "USER": os.getenv("DB_USER", ""),
                "PASSWORD": os.getenv("DB_PASSWORD", ""),
                "HOST": os.getenv("DB_HOST", "localhost"),
                "PORT": os.getenv("DB_PORT", "3306"),
            }
        }
    else:
        raise ImproperlyConfigured(f"Unsupported DB_ENGINE: {DB_ENGINE}")

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = os.getenv("DJANGO_LANGUAGE_CODE", "en-us")
TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "UTC")
USE_I18N = True
USE_TZ = True

# Static & Media
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

MEDIA_URL = os.getenv("DJANGO_MEDIA_URL", "/media/")
MEDIA_ROOT = os.getenv("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media"))

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS and security
CORS_ALLOW_ALL_ORIGINS = get_env_bool("CORS_ALLOW_ALL_ORIGINS", True)
CORS_ALLOWED_ORIGINS = get_env_list("CORS_ALLOWED_ORIGINS", [])
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = get_env_bool("USE_X_FORWARDED_HOST", True)
X_FRAME_OPTIONS = os.getenv("X_FRAME_OPTIONS", "ALLOWALL")

# Email configuration
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = get_env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = get_env_bool("EMAIL_USE_SSL", False)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@example.com")

# API base urls for integration with frontend (documented; not enforced here)
REACT_APP_API_BASE = os.getenv("REACT_APP_API_BASE", "")
REACT_APP_BACKEND_URL = os.getenv("REACT_APP_BACKEND_URL", "")
REACT_APP_FRONTEND_URL = os.getenv("REACT_APP_FRONTEND_URL", "")
REACT_APP_WS_URL = os.getenv("REACT_APP_WS_URL", "")

# Custom User model
AUTH_USER_MODEL = "api.User"

# DRF and JWT configuration
from datetime import timedelta  # noqa: E402

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": int(os.getenv("API_PAGE_SIZE", "20")),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("JWT_ACCESS_MINUTES", "30"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7"))),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": os.getenv("JWT_ALGORITHM", "HS256"),
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
