# Generated by Django 5.2 on 2025-11-11 14:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_existing_through_table(apps, schema_editor):
    """
    For SQLite and other DBs, proactively drop the legacy through table
    created in 0001 (api_answer_selected_choices) before the ManyToMany
    auto-creates its own through table for Answer.selected_choices.
    This avoids 'table already exists' OperationalError.
    """
    table_name = "api_answer_selected_choices"
    with schema_editor.connection.cursor() as cursor:
        vendor = schema_editor.connection.vendor
        if vendor == "sqlite":
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=%s", [table_name])
            exists = cursor.fetchone() is not None
        else:
            # Generic check for other DBs
            try:
                cursor.execute(f"SELECT 1 FROM {table_name} LIMIT 1")
                exists = True
            except Exception:
                exists = False
        if exists:
            schema_editor.execute(schema_editor.sql_delete_table % {"table": schema_editor.quote_name(table_name)})


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Remove FKs on the explicit through model so it can be dropped cleanly
        migrations.RemoveField(
            model_name='answer_selected_choices',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answer_selected_choices',
            name='choice',
        ),
        # Ensure clean state by dropping any leftover table before M2M creation
        migrations.RunPython(drop_existing_through_table, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_action_0a1743_idx',
            old_name='api_audit_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_entity__ad4253_idx',
            old_name='api_audit_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_timesta_da87a7_idx',
            old_name='api_audit_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='api_course_slug_af2ca3_idx',
            old_name='api_course_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='api_course_is_publ_5eb051_idx',
            old_name='api_course_published_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_is_read_b15343_idx',
            old_name='api_notif_read_created_idx',
        ),
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='api_quizatt_passed_07e5b5_idx',
            old_name='api_attempt_passed_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='api_user_usernam_edfd3a_idx',
            old_name='api_user_username_d0dea1_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='api_user_email_a7eefd_idx',
            old_name='api_user_email_2f2a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='api_user_role_9b9076_idx',
            old_name='api_user_role_c2a5b1_idx',
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, to='api.choice'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='api_enrollm_status_8d0e94_idx'),
        ),
        migrations.DeleteModel(
            name='Answer_selected_choices',
        ),
    ]
